---
bump: "patch"
type: "fix"
---

Fix an issue where reporting an exception for a function call whose arguments contain a map of PID would raise a second exception instead.
